### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by froozen** [bjornbm/normaldistribution#1]
There seems to be a problem with normaldistribution and random.

When compiling something using normaldistribution [like this](https://gist.github.com/froozen/7756913d7825c46324f2), the following error arises:

```
[1 of 1] Compiling Main             ( test.hs, test.o )

test.hs:11:23:
    No instance for (random-1.0.1.1:System.Random.RandomGen StdGen)
      arising from a use of ‘normals’
    In the second argument of ‘(.)’, namely ‘normals’
    In the second argument of ‘(.)’, namely ‘take n . normals’
    In the expression: return . take n . normals
```

**Comment by bjornbm** [comment]
The given example compiles without error for me on GHC 7.8.3 (I don't have 7.10.\* available yet).

From the error message my guess is that you have built/installed normaldistribution against version 1.0.1.1 of random, but your test compiles against another version (probably 1.0.1.3 or 1.1). If you load your test file with `:load` in ghci then ghci should tell you which library versions are being used. Perhaps reinstalling normaldistribution will be enough to fix the problem?

It is also possible that an update of dependency bounds is needed for GHC 7.10.*. If that is the case I will happily accept a patch (otherwise it will have to wait until I have opportunity to upgrade my GHC).

**Comment by froozen** [comment]
Yup, it was exactly as you described it. Reinstalling normaldistribution fixed the problem.

Sorry to take your time.

**Comment by bjornbm** [comment]
No problem @froozen.
